strategy:
  maxParallel: "3"
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: "$(imageName)"

steps:
  - script: echo "Hello, World!"
