assert_lefthook_installed: true

post-merge:
  piped: true
  jobs:
    - name: Mise update
      id: mise-update
      run: mise install
      interactive: true

pre-commit:
  piped: true
  jobs:
    - name: "Run formatters"
      run: mise run fmt
      stage_fixed: true
    - name: "Run linters"
      run: mise run lint

prepare-commit-msg:
  piped: true
  jobs:
    - name: "Run commit editor"
      interactive: true
      env: 
        LEFTHOOK: 0
      run: bun run cz --hook

commit-msg:
  piped: true
  jobs:
    - name: "Run commit linter"
      run: bun run commitlint --edit {1}
