assert_lefthook_installed: true

post-merge:
  piped: true
  jobs:
    - name: Mise update
      id: mise-update
      run: mise install
      interactive: true

pre-commit:
  parallel: true
  jobs:
    - name: Documentation
      id: pre-commit-docs
      group:
        piped: true
        jobs:
          - name: Format
            id: fmt-docs
            group:
              parallel: true
              jobs:
                - name: Docs > Format markdown
                  id: fmt-docs-markdown
                  root: src/docs
                  glob: "src/docs/**/*.md"
                  run: mise run mdlint:fix {staged_files}
          - name: Lint
            id: lint-docs
            group:
              parallel: true
              jobs:
                - name: Docs > Lint markdown
                  id: lint-docs-markdown
                  root: src/docs
                  glob: "src/docs/**/*.md"
                  run: mise run mk {staged_files}
    - name: Cli
      id: pre-commit-cli
      group:
        piped: true
        jobs:
          - name: Format
            id: fmt-cli
            group:
              parallel: true
              jobs:
                - name: Cli > Format markdown
                  id: fmt-cli-markdown
                  root: src/cli
                  glob: "src/cli/**/*.md"
                  run: mise run mdlint:fix {staged_files}
          - name: Lint
            id: lint-cli
            group:
              parallel: true
              jobs:
                - name: Cli > Lint markdown
                  id: lint-cli-markdown
                  root: src/cli
                  glob: "src/cli/**/*.md"
                  run: mise run mk {staged_files}
    - name: Lib
      id: pre-commit-lib
      group:
        piped: true
        jobs:
          - name: Format
            id: fmt-lib
            group:
              parallel: true
              jobs:
                - name: Lib > Format markdown
                  id: fmt-lib-markdown
                  root: src/lib
                  glob: "src/lib/**/*.md"
                  run: mise run mdlint:fix {staged_files}
          - name: Lint
            id: lint-lib
            group:
              parallel: true
              jobs:
                - name: Lib > Lint markdown
                  id: lint-lib-markdown
                  root: src/lib
                  glob: "src/lib/**/*.md"
                  run: mise run mk {staged_files}
    - name: OS
      id: pre-commit-os
      group:
        piped: true
        jobs:
          - name: Format
            id: fmt-os
            group:
              parallel: true
              jobs:
                - name: OS > Format markdown
                  id: fmt-markdown
                  root: src/ui
                  glob: "src/os/**/*.md"
                  run: mise run mdlint:fix {staged_files}
          - name: Lint
            id: lint-os
            group:
              parallel: true
              jobs:
                - name: OS > Lint markdown
                  id: lint-os-markdown
                  root: src/os
                  glob: "src/os/**/*.md"
                  run: mise run mk {staged_files}
    - name: UI
      id: pre-commit-ui
      group:
        piped: true
        jobs:
          - name: Format
            id: fmt-ui
            group:
              parallel: true
              jobs:
                - name: UI > Format markdown
                  id: fmt-markdown
                  root: src/ui
                  glob: "src/ui/**/*.md"
                  run: mise run mdlint:fix {staged_files}
          - name: Lint
            id: lint-ui
            group:
              parallel: true
              jobs:
                - name: Lint markdown
                  id: lint-markdown
                  root: src/ui
                  glob: "src/ui/**/*.md"
                  run: mise run mdlint {staged_files}
                - name: Check markdown links  
                  id: check-markdown-links
                  root: src/ui
                  glob: "src/ui/**/*.md"
                  run: mise run mdlinkcheck {staged_files}
    - name: Other
      id: pre-commit-other
      group:
        piped: true
        jobs:
          - name: Format
            id: fmt-other
            group:
              parallel: true
              jobs:
                - name: Other > Format markdown
                  id: fmt-other-markdown
                  glob: "*.md"
                  run: mise run mdlint:fix *.md
          - name: Lint
            id: lint-other
            group:
              parallel: true
              jobs:
                - name: Other > Lint markdown
                  id: lint-other-markdown
                  glob: "*.md"
                  run: mise run mdlinkcheck *.md
