---
MD004:
  style: "consistent"
MD007:
  indent: 2
MD013:
  line_length: 200
MD024:
  siblings_only: true
MD026:
  punctuation: ".,;:!。，；:"
MD029:
  style: "one_or_ordered"
MD033:
  allowed_elements: ["img"]
MD036:
  punctuation: ".,;:!。，；:"
