---
# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false

FILTER_REGEX_EXCLUDE: "(.history|.pixi|megalinter-reports|node_modules|pnpm-lock.yaml|pixi.lock)"
