[tools]
lefthook = "1.11.2"
markdownlint-cli2 = "0.17.2"
gh = "2.67.0"
node = "23.9.0"
pnpm = "10.5.2"

[task_config]
includes = [
  ".config/tasks.md.toml",
  ".config/tasks.rs.toml"
]

[vars]
config_dir = "{{config_root}}/.config"

[env]
CLIPPY_CONF_DIR="{{vars.config_dir}}"

[tasks.fmt]
description = "Run all formatting tasks"
depends = ["fmt:*"]

[tasks.lint]
description = "Run all linting tasks"
depends = ["lint:*"]

[tasks."fix"]
description = "Fix all linting problems"
depends = ["fix:*"]