[tools]
lefthook = "1.11.2"
markdownlint-cli2 = "0.17.2"
gh = "2.67.0"
node = "23.9.0"
pnpm = "10.5.2"
"npm:markdown-link-check" = "3.13.6"

[task_config]
includes = [
  "src/cli/.tasks.toml",
  "src/ui/.tasks.toml",
  "src/os/.tasks.toml",
  "src/lib/.tasks.toml",
  "docs/.tasks.toml",
]

[vars]
config_dir = "{{config_root}}/.config/"
mdlint_config = "{{vars.config_dir}}/.markdownlint-cli2.yaml"
mdlink_check = "{{vars.config_dir}}/.mdlinkcheck.toml"

[tasks.fmt]
description = "Run all formatting tasks"
depends = ["fmt:*", "lint:fix"]

[tasks.lint]
description = "Run all linting tasks"
depends = ["lint:*", "mdlint *.md"]

[tasks."lint:fix"]
description = "Fix all linting problems"
depends = ["lint:*:fix", "mdlint:fix *.md"]

[tasks."markdown:fmt"]
description = "Format markdown files"
usage = 'arg "<file>" var=#true default="*.md"'
quiet = true
run = '''
  mise run mdlint:fix {{arg(name="file")}}
'''

[tasks."markdown:lint"]
description = "Lint markdown files"
usage = 'arg "<file>" var=#true default="*.md"'
quiet = true
run = '''
  mise run mdlint {{arg(name="file")}}
  mise run mdlinkcheck {{arg(name="file")}}
'''

## Internal Tasks - Prefer running the tasks above instead ##

[tasks.mdlint]
hide = true
usage = 'arg "<file>" var=#true default="*.md"'
run = 'markdownlint-cli2 --config {{vars.mdlint_config}} {{arg(name="file")}}'

[tasks."mdlint:fix"]
hide = true
usage = 'arg "<file>" var=#true default="*.md"'
run = 'mise run mdlint {{arg(name="file")}} -- --fix'

[tasks.mdlinkcheck]
hide = true
usage = 'arg "<file>" var=#true default="*.md"'
run = 'markdown-link-check {{arg(name="file")}}'
