[workspace]
members = [
    "lib",
    "cli",
    "ui",
    "platforms/windows",
    "platforms/macos",
    "platforms/linux",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Pierre Fouilloux <pfxdev@noreply.hibiscusgames.com>"]
description = "Git things done — right from the context menu. No commands, no clutter, just like magic."
license = "Hippocratic-3.0"
license-file = "LICENSE"
repository = "https://codeberg.org/HibiscusCollective/gitnavi"

[workspace.dependencies]
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
