[tools]
lefthook = "1.11.2"
node = "23.9.0"
pnpm = "10.5.2"
rust = "1.85.0"

[task_config]
includes = [
    "src/cli/.tasks.toml",
    "src/ui/.tasks.toml",
    "src/os/.tasks.toml",
    "src/lib/.tasks.toml",
]

[tasks.fmt]
depends = ["fmt:*"]

[tasks.lint]
depends = ["lint:*"]
