[tools]
node = "22.12.0"
pnpm = "9.15.0"

[settings]
experimental = true # Require for hooks

[env]
NODE_ENV = "development"

[[watch_files]]
patterns = ["pixi.lock", "mise.toml"]
run = "pixi install && mise install"
