[project]
authors = ["Pierre Fouilloux <pfxdev@noreply.codeberg.org>"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
channels = ["conda-forge"]
name = "GitNavi"
description = "Git things done — right from the context menu. No commands, no clutter, just like magic."
version = "0.1.0"
license-file = "LICENSE"
readme = "README.md"
repository = "https://codeberg.org/HibiscusCollective/gitnavi"

[tasks]
lint = "echo Hello"

[build-dependencies]
nodejs = ">=22.12.0,<22.13"
pnpm = ">=9.15.0,<10"

[host-dependencies]
rust = ">=1.83.0,<1.84"
tauri = ">=2.1.0,<3"
lefthook = ">=1.9.2,<2"
