["fmt:ui"]
description = "Runs formatters on the code"
depends = ["fmt:ui"]

["lint:ui"]
description = "Runs linters on the code"
depends = ["mdlint src/ui/**/*.md"]

["lint:ui:fix"]
description = "Fix all linting problems"
depends = ["mdlint:fix src/ui/**/*.md"]