[package]
name = "gitnavi-windows"  # Not published to crates.io
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
description = "Windows-specific installer and context menu integration for GitNavi"
publish = false  # Prevent accidental publishing

[dependencies]
gitnavi = { path = "../../lib" }
gitnavi-ui = { path = "../../ui" }
windows = "0.52"  # For Windows API integration
tokio.workspace = true
