name: Linting Checks

permissions:
    contents: read

on:
    push:
    pull_request:

jobs:
    rust:
        runs-on: ubuntu-24.04
        permissions:
            contents: read
        container:
            image: rust:1.85-slim-bullseye
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            - run: |
                  curl https://mise.run | sh
                  mise install
            - run: mise lint
